<template>
  <view class="trend-insight">
    <view class="list-meta"><text class="list-title">趋势股列表</text><view class="list-meta-right"><view class="list-action" @tap="openPodcast"><SvgIcon name="broadcast-line" size="30rpx" color="#0b5fff" /></view><view class="list-action" @tap="refresh"><SvgIcon name="refresh-line" size="32rpx" color="#0b5fff" /></view><text v-if="latestDate" class="updated-date">{{ latestDate }}</text><text class="stock-count">{{ filteredStocks.length }} 只</text></view></view>
    <LoadingState v-if="loading" text="正在加载趋势评分" />
    <view v-else-if="errorMessage" class="state-panel"><SvgIcon name="error-warning-line" size="64rpx" color="#f59e0b" /><text class="state-title">趋势评分暂时无法加载</text><text class="state-desc">{{ errorMessage }}</text><button class="retry-button" @tap="loadTopStocks">重新加载</button></view>
    <EmptyState v-else-if="!filteredStocks.length" icon="search-eye-line" text="没有找到匹配的趋势股" />
    <view v-else class="stock-list"><view v-for="stock in filteredStocks.slice(0, 5)" :key="stock.symbol" class="stock-row" @tap="openDetail(stock)"><view class="stock-main"><text class="stock-name">{{ stock.name || stock.symbol }}</text><view class="stock-meta"><text class="stock-symbol">{{ stock.symbol }}</text><text v-if="stock.industry" class="industry-tag">{{ stock.industry }}</text></view></view><view class="score-block"><text class="total-score">{{ stock.score }}</text></view><text :class="['grade', `grade-${stock.label.toLowerCase()}`]">{{ stock.label }}</text><SvgIcon name="arrow-right-s-line" size="30rpx" color="#c6cad2" /></view><view v-if="filteredStocks.length > 5" class="view-all" @tap="goAll">查看全部 <text>›</text></view><view class="list-footnote">评分基于公开数据与模型测算，仅供参考，不构成投资建议。</view></view>
  </view>
</template>
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { trendScoreApi, type TrendScoreListItem } from '@/shared/api/modules/trend-score'
import SvgIcon from '@/shared/components/SvgIcon.vue'
import LoadingState from '@/shared/components/LoadingState.vue'
import EmptyState from '@/shared/components/EmptyState.vue'
import { useReportPodcast } from '@/shared/utils/useReportPodcast'
const { loadPodcast, openPodcast: showPodcast } = useReportPodcast('trend_score')
const stocks = ref<TrendScoreListItem[]>([]); const loading = ref(false); const errorMessage = ref('')
const filteredStocks = computed(() => stocks.value)
const latestDate = computed(() => String(stocks.value[0]?.scoreDate || '').slice(0, 10))
async function loadTopStocks() { loading.value = true; errorMessage.value = ''; try { const result = await trendScoreApi.getTop(30); stocks.value = Array.isArray(result) ? result : [] } catch (error: unknown) { const item = error as { errMsg?: string; message?: string }; errorMessage.value = item.errMsg || item.message || '请稍后重试' } finally { loading.value = false } }
function openDetail(stock: TrendScoreListItem) { const name = encodeURIComponent(stock.name || stock.symbol); uni.navigateTo({ url: `/modules/analytics/pages/trend-score-detail?symbol=${stock.symbol}&name=${name}` }) }
function goAll() { uni.navigateTo({ url: '/modules/analytics/pages/trend-score' }) }
function openPodcast() { showPodcast('趋势股评分播报') } function refresh() { void loadTopStocks() }
onMounted(() => { void loadTopStocks(); void loadPodcast() })
</script>
<style lang="scss" scoped>
.search-wrap{height:76rpx;margin:0 0 $spacing-sm;padding:0 $spacing-base;display:flex;align-items:center;gap:$spacing-sm;border:1rpx solid $border-color-light;border-radius:$radius-base;background:$bg-color-grey;box-shadow:$shadow-base}.search-input{flex:1;height:100%;color:$text-color;font-size:$font-size-base}.search-placeholder{color:$text-color-tertiary}.list-meta{display:flex;align-items:center;justify-content:space-between;margin:$s-2 0;min-height:44rpx}.list-title{color:$ink;font-size:$font-size-base;font-weight:600}.list-meta-right{display:flex;align-items:center;gap:$s-1}.list-action{width:44rpx;height:44rpx;display:flex;align-items:center;justify-content:center}.updated-date{color:$ink-mute;font-size:$font-size-xs}.stock-count{padding:4rpx 14rpx;border-radius:$r-xs;color:$primary;background:$primary-50;font-size:$font-size-xs;font-weight:600}.stock-list{display:flex;flex-direction:column;gap:$s-2}.stock-row{min-height:116rpx;display:flex;align-items:center;gap:$s-2;padding:$s-3;border:1rpx solid $line;border-radius:$r-lg;background:$bg-card;box-shadow:$shadow-sm}.stock-main{flex:1;min-width:0}.stock-name{display:block;overflow:hidden;color:$ink;font-size:$font-size-md;font-weight:600;text-overflow:ellipsis;white-space:nowrap}.stock-meta{margin-top:$s-1;display:flex;align-items:center;gap:$s-1}.stock-symbol{color:$ink-mute;font-size:$font-size-xs;font-weight:500}.industry-tag{max-width:160rpx;overflow:hidden;padding:2rpx 10rpx;border-radius:$r-xs;color:$ink-soft;background:$bg-soft;font-size:$font-size-xs;text-overflow:ellipsis;white-space:nowrap}.score-block{width:56rpx;flex-shrink:0;display:flex;justify-content:flex-end}.total-score{color:$primary;font-size:$font-size-lg;font-weight:750}.grade{width:44rpx;height:44rpx;flex-shrink:0;display:flex;align-items:center;justify-content:center;border-radius:$r-sm;color:#fff;background:$primary;font-size:$font-size-base;font-weight:750}.grade-s{background:$up}.grade-a{background:$primary}.grade-b,.grade-c,.grade-d{background:$ink-soft}.view-all{padding:$s-2 $s-3 $s-2;color:$ink-mute;font-size:$font-size-base;text-align:center}.list-footnote{padding:$s-3 $s-2;color:$ink-mute;font-size:$font-size-xs;line-height:1.6;text-align:center}.state-panel{padding:$s-10 $s-4;display:flex;flex-direction:column;align-items:center;border-radius:$r-lg;background:$bg-card}.state-title{margin-top:$s-2;color:$ink;font-size:$font-size-lg;font-weight:600}.state-desc{margin-top:$s-1;color:$ink-soft;font-size:$font-size-sm;text-align:center}.retry-button{margin-top:$s-3;padding:0 $s-4;border:0;border-radius:$r-full;background:$primary;color:$bg-card;font-size:$font-size-sm;line-height:64rpx}.retry-button::after{border:0}
</style>
